### PR TITLE
Don't catch async exceptions.

### PR DESCRIPTION
**Pull request by chpatrick**
This change is [Reviewable](https://reviewable.io/reviews/chpatrick/solga/5)

### CODE REVIEW

**Comment by bitonic** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[solga/src/Solga.hs, line 103 [r1]](https://reviewable.io:443/reviews/chpatrick/solga/5#-KM4A7Oarn9b13XXphL9:-KM4A7Oarn9b13XXphLA:661736879) ([raw file](https://github.com/chpatrick/solga/blob/a225e62632c3b62a571e58d4bc086160913d57a6/solga/src/Solga.hs#L103)):_

> ``` Haskell
> -- | Serve a `Router` with Solga, returning `SolgaError`s as HTTP responses.
> serve :: Router r => r -> Wai.Application
> serve router req cont = serveThrow router req cont
> ```

This is dangerous, for the reasons described here: https://www.stackage.org/haddock/lts-6.6/base-4.8.2.0/Control-Exception.html#v:catches

@snoyberg , shouldn't we provide `catches` in `safe-exceptions`?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/chpatrick/solga/5)_

**Comment by chpatrick** [comment]
_[solga/src/Solga.hs, line 103 [r1]](https://reviewable.io:443/reviews/chpatrick/solga/5#-KM4A7Oarn9b13XXphL9:-KM4WbWcY5GTh6UTEZ-f:-499146009) ([raw file](https://github.com/chpatrick/solga/blob/a225e62632c3b62a571e58d4bc086160913d57a6/solga/src/Solga.hs#L103)):_
<details><summary>

<i>Previously, bitonic (Francesco Mazzoli) wrote…</i></summary>



> This is dangerous, for the reasons described here: https://www.stackage.org/haddock/lts-6.6/base-4.8.2.0/Control-Exception.html#v:catches
> 
> @snoyberg , shouldn't we provide `catches` in `safe-exceptions`?
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/chpatrick/solga/5)_

**Comment by bitonic** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[solga/src/Solga.hs, line 109 [r2]](https://reviewable.io:443/reviews/chpatrick/solga/5#-KM4X-5tEV6YxIsQQPVm:-KM4X-5tEV6YxIsQQPVn:-1538281185) ([raw file](https://github.com/chpatrick/solga/blob/2f652f52cd4779d108dca4de854e7d9865941c92/solga/src/Solga.hs#L109)):_

> ``` Haskell
>       ( status, body ) = case cast ex of
>         Just SolgaError { errorStatus, errorMessage } -> ( errorStatus, Builder.byteString $ encodeUtf8 errorMessage )
>         Nothing -> ( HTTP.internalServerError500, mempty )
> ```

Wouldn't it be best practice to have a minimal body? E.g. "Internal Server error"?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/chpatrick/solga/5)_

**Comment by chpatrick** [comment]
_[solga/src/Solga.hs, line 109 [r2]](https://reviewable.io:443/reviews/chpatrick/solga/5#-KM4X-5tEV6YxIsQQPVm:-KM4Xgl77d4DkW7mE4gg:-499146009) ([raw file](https://github.com/chpatrick/solga/blob/2f652f52cd4779d108dca4de854e7d9865941c92/solga/src/Solga.hs#L109)):_
<details><summary>

<i>Previously, bitonic (Francesco Mazzoli) wrote…</i></summary>



> Wouldn't it be best practice to have a minimal body? E.g. "Internal Server error"?
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/chpatrick/solga/5)_

**Comment by bitonic** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/chpatrick/solga/5)_

**Comment by snoyberg** [comment]
> @snoyberg , shouldn't we provide catches in safe-exceptions?

I see no reason why not, wanna open an issue or PR?

**Pull request closed without merging**
